export const cartActionTypes = {
    TOGGLE_CARTDROPDOWN: 'TOGGLE_CARTDROPDOWN',
    ADD_ITEM: 'ADD_ITEM',
    REDUCE_ITEM: 'REDUCE_ITEM',
    REMOVE_ITEM_FROM_CART: 'REMOVE_ITEM_FROM_CART',
    CLEAR_CART:'CLEAR_CART'
}

export default cartActionTypes;